# Generated by Django 3.2.13 on 2022-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulc_api', '0003_auto_20220611_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='Null', max_length=30),
            preserve_default=False,
        ),
    ]
