# Generated by Django 3.2.13 on 2022-06-13 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulc_api', '0004_userprofile_last_name'),
    ]

    operations = [
        migrations.RenameModel('ProfileFeedItem', 'Property'),
    ]
