# Generated by Django 3.2.13 on 2022-06-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulc_api', '0005_auto_20220613_0351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='ProfileFeedItem',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
