# Generated by Django 3.2.13 on 2022-06-13 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulc_api', '0006_auto_20220613_0402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
